### ISSUE TITLE
Need to create a README.md with a getting started section people who want to use the library

### ISSUE THREAD

**Issue by OleDakotaJoe** [open-code-academy/community-ui#11]
As a developer who is getting started with the project, it should be well outlined how to start up the project and get started. To solve this, the project should have a README.md that should have a "Getting Started" section for development, and running the storybook server. 

Acceptance Criteria:
- README.md created
- Getting started section is created, and explains how to start the storybook server.

**Comment by OleDakotaJoe** [comment]
Thanks for doing this @CasuallyCaffeinated !

**Comment by CasuallyCaffeinated** [comment]
Of course! Now we need to see what we can add to the README for issue #7 https://github.com/open-code-academy/community-ui/issues/7
