### ISSUE TITLE
Add a Prettier config file for consistent code formatting

### ISSUE THREAD

**Issue by Ayon95** [open-code-academy/community-ui#12]
It is important to make sure that everyone contributing code to a project follows a specific style guide. Consistently formatted code is easier to read and reason about. This is why the project requires a Prettier config file that should contain a configuration that everyone agrees with.

Acceptance criteria:
- .prettierrc file is created and populated with configuration options
- In CONTRIBUTING.md, a "Style Guide" section is created specifying that code must be formatted according to the project's Prettier configuration before adding it.

**Comment by OleDakotaJoe** [comment]
Thanks for raising the issue
