### ISSUE TITLE
Need to set up npm project

### ISSUE THREAD

**Issue by OleDakotaJoe** [open-code-academy/community-ui#2]
As a developer who might want to consume the CommunityUI library, it would be helpful to have the UI library available in NPM so that we can easily distribute and consume the project in other projects for use. Also, we want to make sure that someone doesn't steal our name. So we will test this by deploying just a readme as our version 0.0.0

Acceptance criteria:

- npm project setup (package.json) 
- only the library's source code is distributed via npm, not storybook implementation
- version 0.0.0 is published
- README.md is included
- CONTRIBUTING.md is excluded
- LICENSE is included
- no other *.md files are included except README.md
- should support typescript

**Comment by aetheode** [comment]
What do you mean exactly that "version 0.0.0 is deployed"

**Comment by OleDakotaJoe** [comment]
I'll add more context. 
Basically, just do a test to lock in the name, (so someone else doesn't take our package name by some crazy misfortune) and deploy a readme that is coming soon

**Comment by aetheode** [comment]
Ahhh you mean published

**Comment by OleDakotaJoe** [comment]
Also, just wanted to note here, whoever does this will need to get with me to get access via npm account
