### ISSUE TITLE
ToggleButton Component

### ISSUE THREAD

**Issue by OleDakotaJoe** [open-code-academy/community-ui#25]
As a developer who will be implementing the library, I would like to have a easily groupable set of toggle buttons, that can toggle functionality on and off. In order for this to be useful, it must interface with a container, that can utilize the buttons to create a toggle button group. These should be square buttons, simliar to the MaterialUI concept of a toggle button and a toggle button group.

Acceptance Criteria: 
- Buttons can toggle on and off
- Buttons interface with a ToggleButtonGroup component
-

**Comment by natoh19** [comment]
Giving this one a go...no idea how to do this however lol
