### ISSUE TITLE
Need to integrate with husky and commitlint to screen pre-commit hoooks

### ISSUE THREAD

**Issue by OleDakotaJoe** [open-code-academy/community-ui#3]
As a developer using the project, since we will be using semantic-release, it will be helpful to know that the commit messages I am providing are not properly formatted to follow the[ conventional commits standards](https://www.conventionalcommits.org/en/v1.0.0-beta.2/). 

Need to integrate the[ husky](https://typicode.github.io/husky/#/) 
and set up [commitlint](https://commitlint.js.org/#/) to reject commits that are not following convential commits standards.

Acceptance Criteria:
- Husky pre-commit hooks setup
- commitlint set up as a pre-commit hook and validates that commits are following conventional commits standards
- `npm run` scripts written to install these projects on `npm install` (if possible) (look up npm install lifecycle hooks)

**Comment by CasuallyCaffeinated** [comment]
Looking into this today

**Comment by OleDakotaJoe** [comment]
Merged
