### ISSUE TITLE
Write tests for ButtonStyle.utils

### ISSUE THREAD

**Issue by OleDakotaJoe** [open-code-academy/community-ui#36]
As a developer, it would be helpful to know that we have not broken any existing features. In order to do this, we want to have as much reasonable test coverage as possible. 

Acceptance Criteria: 
- Unit tests written for ButtonStyle.utils
- Tests pass

**Comment by Ayon95** [comment]
I'd like to work on this issue.

**Comment by OleDakotaJoe** [comment]
Forgive my brevity in the issue description. Just read that and probably could have done better kn that one

**Comment by Ayon95** [comment]
Haha no worries. It was good enough for me to get started.
