### ISSUE TITLE
Refactor the project to improve organization

### ISSUE THREAD

**Issue by OleDakotaJoe** [open-code-academy/community-ui#48]
In order to improve discoverability of components and the logical organization of components, the project shoud be re-organized. 

An example of a soution is provided below:

├── components
│   ├── Buttons
│   │   ├── AnimatedButton
│   │   ├── BaseButton
│   │   │   ├── ButtonBase.component.tsx
│   │   │   ├── ButtonBase.test.tsx
│   │   │   ├── index.ts
│   │   │   └── TextButtonBase.component.tsx
│   │   ├── common
│   │   │   ├── styles
│   │   │   │   └── ButtonStyles.styles.ts
│   │   │   ├── types
│   │   │   │   └── Button.types.ts
│   │   │   └── utils
│   │   │       ├── ButtonStyle.utils.test.ts
│   │   │       ├── ButtonStyle.utils.ts
│   │   │       └── index.ts
│   │   ├── index.ts
│   │   └── PlainButton
│   └── index.ts
├── core
│   ├── css-utils
│   │   └── Mixins.styles.ts
│   └── theme
│       ├── constants
│       │   ├── Button.constants.ts
│       │   ├── Colors.constants.ts
│       │   └── DefaultSizes.constants.ts
│       ├── default
│       │   └── Default.theme.ts
│       ├── index.ts
│       ├── theme-resolver
│       └── types
│           ├── Colors.types.ts
│           └── Sizes.types.ts
└── index.ts

Acceptance Criteria: 
- Project is restructured
- All components and directories are logically organized
- Project structure mental model is documented in CONTRIBUTING.md

**Comment by Ayon95** [comment]
I'd like to work on this issue.
