### ISSUE TITLE
Semantic Release integration

### ISSUE THREAD

**Issue by OleDakotaJoe** [open-code-academy/community-ui#5]
As a developer, it would be helpful to not have any manual processes for releasing CommunityUI. 
For this, we will use [semantic-release](https://semantic-release.gitbook.io/semantic-release/). 
The goal here is to make sure that whenever we merge our branch with main, a release takes place automatically, and updates to the proper version of the package. The semantic-release utility can be configured to do this automatically.

Acceptance Criteria: 
- semantic release integrated
- configured to release to our project in npm
- test release ran to be sure

**Comment by ashes4trees** [comment]
I'd love to tackle this issue... I'm not able to assign myself, just wanted to flag it so we don't have overlap.

**Comment by OleDakotaJoe** [comment]
Yes absolutely. I'll add you to the org Soni can assign it tonyou

**Comment by OleDakotaJoe** [comment]
Integration was spot on. 
We are on v1.0.0 now (lol oops), so now, we're switching to the develop branch until any churn that exists dies down, and then we will start merging to main again.
