### ISSUE TITLE
Spike: Determine the first several components to be made

### ISSUE THREAD

**Issue by OleDakotaJoe** [open-code-academy/community-ui#8]
As a developer contributing to this project, there should be a bounty of work to be completed, so that no-one is waiting for work to complete. 

In order to facilitate, a brainstorm session needs to take place and a list of components needs to be documented, as well as their relationship to each other needs to be established so that several components can be started at the same time, and their priority can be set. 

Acceptance Criteria:
- List of initial components created and documented in Roadmap section of README.md
- Issues created for getting these components built and added to storybook

**Comment by raop155** [comment]
ATOM Componentes (BASE):

- < Button /> (submit)
- < Input /> (text, number, radio, checkbox, textarea)
- < Select />
- < Textarea /> (separate from  < Input /> comp?)


- < Typography /> (div, label, h1...h6, p, span)
- < DatePicker /> (with moment? This is tricky :P)

**Comment by OleDakotaJoe** [comment]
I've got these listed as well

CommunityUI Components

Rounded Button
Pill Button
ButtonWithArrow (animated and static)
ToggleButtonGroup
    - ToggleButtons
ToggleSwitches
Cards
    - FlipCard
    - ImageCard
    -  UserCard
    -  ProductCard
Header (different styles)
    - Hamburger Button (multiple variations and animations)
    -  BrandLogo
    -  DropdownMenu
    -  MenuItem
    -  CartItem
    -  Cart
    -  Navigation
    -  Profile/Account Icons
    -  Notification Icons
Inputs
    -  TextFields
    -  MultilineTextField
    -
